routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Repositories\BlogRepository as BlogRepo;
use App\Language;

Auth::routes();
Route::prefix('manage')->middleware('role:superadmin|testsuperadmin|admin|testadmin|editor|author|contributor')->group(function () {
    Route::get('/', 'BackEndController@index');
    Route::get('/dashboard', 'BackEndController@dashboard')->name('manage.dashboard');
    Route::resource('/settings', 'SettingController');
    Route::resource('/profile', 'ProfileController');
    Route::resource('/users', 'UserController');
    Route::resource('/permissions', 'PermissionController', ['except' => 'destroy'])->middleware('role:superadmin');
    Route::resource('/roles', 'RoleController', ['except' => 'destroy'])->middleware('role:superadmin');
    Route::resource('/posts', 'PostController');
    Route::resource('/categories', 'CategoryController', ["except" => ["create"]]);
    Route::resource('/languages', 'LanguageController', ["except" => ["create"]]);
    Route::resource('/tags', 'TagController', ["except" => ["create"]]);
    Route::get('media/{folder?}', 'MediaController@index')->where('folder', '.*');
    Route::resource('media', 'MediaController');
    Route::post('upload/avatar', 'ProfileController@file');
    Route::post('upload/favicon', 'SettingController@file');
});
Route::get('/home', 'HomeController@index')->name('home');
if(Schema::hasTable('settings') && Schema::hasTable('languages')){
    $metaBlog = (new BlogRepo)->getSettings();
    $blog_slug = $metaBlog['blog_slug'];
    // $blog_slug = 'hgfhdfgh';
    if ($metaBlog['disable_language_group']) {
        Route::get('/', function () use($blog_slug){
            return redirect($blog_slug);
        });
        Route::get('/{lang}/'.$blog_slug, function () use($blog_slug) {
            return redirect($blog_slug);
        });
        
        Route::prefix($blog_slug)->group(function ($lang) use($blog_slug) {
            Route::get('/', ['uses' => 'FrontEndController@blog', 'blog_slug' => $blog_slug])
                ->name('blog');
            Route::get('/{year?}/{month?}/{day?}', ['uses' => 'BlogController@getBlogDate', 'blog_slug' => $blog_slug])
                ->name('blog.date')
                ->where('year', '[0-9]+')
                ->where('month', '[0-9]+')
                ->where('day', '[0-9]+')
                ->defaults('year', false)
                ->defaults('month', false)
                ->defaults('day', false);
            Route::get('/{slug?}', ['uses' => 'BlogController@getSingle', 'blog_slug' => $blog_slug])
                ->name('blog.single')
                ->where('slug', '[\w\d\-\_]+');
            Route::get('/{year}/{month}/{slug}', ['uses' => 'BlogController@getSingle', 'blog_slug' => $blog_slug])
                ->name('blog.singleYearMonth')
                ->where('year', '[0-9]+')
                ->where('month', '[0-9]+')
                ->where('slug', '[\w\d\-\_]+');
            Route::get('/{year}/{month}/{day}/{slug}', ['uses' => 'BlogController@getSingle', 'blog_slug' => $blog_slug])
                ->name('blog.singleYearMonthDay')
                ->where('year', '[0-9]+')
                ->where('month', '[0-9]+')
                ->where('day', '[0-9]+')
                ->where('slug', '[\w\d\-\_]+');

            Route::get('/category/{slug?}', ['uses' => 'BlogController@getBlogCategory', 'blog_slug' => $blog_slug])
                ->name('blog.category')
                ->where('slug', '[\w\d\-\_]+');
            Route::get('/tag/{slug?}', ['uses' => 'BlogController@getBlogTag', 'blog_slug' => $blog_slug])
                ->name('blog.tag')
                ->where('slug', '[\w\d\-\_]+');
            Route::get('/author/{slug?}', ['uses' => 'BlogController@getBlogAuthor', 'blog_slug' => $blog_slug])
                ->name('blog.author')
                ->where('slug', '[\w\d\-\_]+');
        });
    } else {
        $lang = Language::All();
        Route::get('/{slug?}', function () use ($lang, $blog_slug) {
            $localCode = app()->getLocale();
            if (!$localCode) {
                $localCode = $lang[0]->slug;
            }
            return redirect($localCode.'/'.$blog_slug);
        });
        Route::get('/'.$blog_slug, function () use ($lang, $blog_slug) {
            $localCode = app()->getLocale();
            if (!$localCode) {
                $localCode = $lang[0]->slug;
            }
            // return redirect(App::getLocale().'/blog');
            return redirect($localCode.'/'.$blog_slug);
        });
        // Route::get('/{slug}', function () {
        //     $localCode = app()->getLocale();
        //     if(!$localCode) $localCode = $lang[0]->slug;
        //     // return redirect(App::getLocale().'/blog');
        //     return redirect($localCode.'/'.$blog_slug);
        // });
        Route::prefix('{lang?}/'.$blog_slug)->group(function ($lang) use ($blog_slug) {
            // App::setLocale($lang);
            Route::get('/', ['uses' => 'FrontEndController@blog', 'blog_slug' => $blog_slug])
                ->name('blog')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', 'en');
            Route::get('/{year?}/{month?}/{day?}', ['uses' => 'BlogController@getBlogDate', 'blog_slug' => $blog_slug])
                ->name('blog.date')
                ->where('lang', '[\w\d\-\_]+')
                ->where('year', '[0-9]+')
                ->where('month', '[0-9]+')
                ->where('day', '[0-9]+')
                ->defaults('lang', false)
                ->defaults('year', false)
                ->defaults('month', false)
                ->defaults('day', false);
            Route::get('/{slug?}', ['uses' => 'BlogController@getSingle', 'blog_slug' => $blog_slug])
                ->name('blog.single')
                ->where('slug', '[\w\d\-\_]+')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', false);
            Route::get('/{year}/{month}/{slug}', ['uses' => 'BlogController@getSingle', 'blog_slug' => $blog_slug])
                ->name('blog.singleYearMonth')
                ->where('year', '[0-9]+')
                ->where('month', '[0-9]+')
                ->where('slug', '[\w\d\-\_]+')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', false);
            Route::get('/{year}/{month}/{day}/{slug}', ['uses' => 'BlogController@getSingle', 'blog_slug' => $blog_slug])
                ->name('blog.singleYearMonthDay')
                ->where('year', '[0-9]+')
                ->where('month', '[0-9]+')
                ->where('day', '[0-9]+')
                ->where('slug', '[\w\d\-\_]+')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', false);

            Route::get('/category/{slug?}', ['uses' => 'BlogController@getBlogCategory', 'blog_slug' => $blog_slug])
                ->name('blog.category')
                ->where('slug', '[\w\d\-\_]+')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', false);
            Route::get('/tag/{slug?}', ['uses' => 'BlogController@getBlogTag', 'blog_slug' => $blog_slug])
                ->name('blog.tag')
                ->where('slug', '[\w\d\-\_]+')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', false);
            Route::get('/author/{slug?}', ['uses' => 'BlogController@getBlogAuthor', 'blog_slug' => $blog_slug])
                ->name('blog.author')
                ->where('slug', '[\w\d\-\_]+')
                ->where('lang', '[\w\d\-\_]+')
                ->defaults('lang', false);
        });
    }

    Route::get('locale/{locale}/{page?}', function ($locale, $page=false) use($blog_slug) {
        \Session::put('locale', $locale);
        $in = url()->previous();
        $count = strlen(url('/'))+1;
        $in2 = substr($in, $count);
        $in2 = strstr($in2, '/');
        if ($page == 'single') {
            return redirect(url('/').'/'.$locale.'/'.$blog_slug);
        } else {
            return redirect(url('/').'/'.$locale.$in2);
        }
    });
}

app/Http/Controllers/BackEndController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Tag;
use App\Language;
use App\User;
class BackEndController extends Controller
{
    public function index()
    {
      return redirect()->route('manage.dashboard');
    }

    public function dashboard()
    {
      $number = [
        'posts' => Post::count(),
        'cats' => Category::count(),
        'tags' => Tag::count(),
        'langs' => Language::count(),
        'users' => User::count()
      ];
      return view('back-end.dashboard')->with('num', $number);
    }

    public function profile()
    {
      return view('back-end.profile');
    }

    public function settings()
    {
      return view('back-end.settings');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use DB;
use Session;
use Hash;
use Input;
use Auth;
use App\Http\Requests\UserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $access = Auth::user()->can('read-users');
        if (!$access) {
            abort(403);
        }
        $users = User::orderBy('id', 'desc')->paginate(10);
        return view('back-end.users.index')->withUsers($users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $access = Auth::user()->can('create-users');
        if (!$access) {
            abort(403);
        }

        $roles = Role::all();
        $maxId = User::max('id');

        $user = (object)[
          'id'=>$maxId+1,
          'display_name'=> '',
          'name'=> '',
          'email'=> '',
          'roles'=> collect(['id'=>'']),
        ];
        $page = 'Create User';
        $title_text = '<i class="fa fa-user-plus m-r-10"></i>';
        return view("back-end.users.create-edit")
        ->withUser($user)
        ->withRoles($roles)
        ->with('page', $page)
        ->with('title_text', $title_text);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $access = Auth::user()->can('create-users');
        if (!$access) {
            abort(403);
        }
        $maxId = User::max('id');
        // if (!empty($request->password)) {
        //   $password = trim($request->password);
        // } else {
        //   # set the manual password
        //   $length = 10;
        //   $keyspace = '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ';
        //   $password = '';
        //   $max = mb_strlen($keyspace, '8bit') - 1;
        //   for ($i = 0; $i < $length; ++$i) {
        //       $password .= $keyspace[random_int(0, $max)];
        //   }
        //   $password = $password;
        // }
        $user = new User();
        $user->id = $maxId+1;
        $user->display_name = $request->display_name;
        $user->name = $request->name;
        $user->email = $request->email;
        $password = '';
        $is_rand_pass_passed = false;
        if ($request->password_options == 'auto') {
            $length = 10;
            $keyspace = '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ';
            $password = '';
            $max = mb_strlen($keyspace, '8bit') - 1;
            for ($i = 0; $i < $length; ++$i) {
                $password .= $keyspace[random_int(0, $max)];
            }
            $user->password = Hash::make($password);
            $is_rand_pass_passed = true;
        } elseif ($request->password_options == 'manual') {
            $user->password = Hash::make($request->password);
        }
        // $user->password = Hash::make($password);
        $user->save();
        if ($request->roles) {
            $user->syncRoles($request->roles);
        }
        // return redirect()->route('users.show', $user->id)->with('password', $password);
        return redirect()->route('users.show', $user->id)->with('pass', $password)->with('is_rand_pass_passed', $is_rand_pass_passed);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $access = Auth::user()->can('read-users');
        if (!$access) {
            abort(403);
        }
        $id = (int)$id;
        $user = User::where('id', $id)->with('roles')->first();
        return view("back-end.users.show")->withUser($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $access = Auth::user()->can('update-users');
        if (!$access) {
            abort(403);
        }
        $id = (int)$id;
        $roles = Role::all();
        $user = User::where('id', $id)->with('roles')->first();
        $page = 'Editing User';
        $title_text = '<i class="fa fa-user-plus m-r-10"></i>';
        return view("back-end.users.create-edit")
        ->withUser($user)
        ->withRoles($roles)
        ->with('page', $page)
        ->with('title_text', $title_text);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        $access = Auth::user()->can('update-users');
        if (!$access) {
            abort(403);
        }
        $id = (int)$id;
        $user = User::findOrFail($id);
        $user->display_name = $request->display_name;
        $user->email = $request->email;
        $user->name = $request->name;
        $password = '';
        $is_rand_pass_passed = false;
        if ($request->password_options == 'auto') {
            $length = 10;
            $keyspace = '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ';
            $password = '';
            $max = mb_strlen($keyspace, '8bit') - 1;
            for ($i = 0; $i < $length; ++$i) {
                $password .= $keyspace[random_int(0, $max)];
            }
            $user->password = Hash::make($password);
            $is_rand_pass_passed = true;
        } elseif ($request->password_options == 'manual') {
            $user->password = Hash::make($request->password);
        }
        $user->save();
        $user->syncRoles($request->roles);
        return redirect()->route('users.show', $id)->with('pass', $password)->with('is_rand_pass_passed', $is_rand_pass_passed);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $access = Auth::user()->can('delete-users');
        if (!$access) {
            abort(403);
        }
    }
}

resources/views/back-end/users/create-edit.blade.php
{{-- @extends('layouts.manage', ['title_text' => $title_text, 'item_type' => $page]) --}}
@extends('layouts.manage', ['title_text' => $title_text, 'item_type' => $page, 'customButton' => 
'<button form="form" class="button is-success is-pulled-right"><i class="fa fa-save"></i><span class="m-l-15">Save</span></button>'
])
@section('content')
    @if (!Route::is('users.create'))
        <form id="form" action="{{route('users.update', $user->id)}}" method="post">
    @else
        <form id="form" action="{{route('users.store')}}" method="post">
    @endif
        {{ csrf_field() }}
        @if (!Route::is('users.create'))
            {{method_field('PUT')}}
        @endif
        <div class="columns is-marginless">
            <div class="column is-paddingless">
                <div class="card full-height">
                    <div class="card-content">
                        <div class="field">
                            <label for="name" class="label">Name:</label>
                            <p class="control">
                                <input type="text" class="input" name="display_name" id="name" value="{{$user->display_name}}">
                            </p>
                        </div>
                        <div class="field">
                            <label for="username" class="label">Username:</label>
                            <p class="control">
                                <input type="text" class="input" name="name" id="username" value="{{$user->name}}">
                            </p>
                        </div>
                        <div class="field">
                            <label for="email" class="label">Email:</label>
                            <p class="control">
                                <input type="text" class="input" name="email" id="email" value="{{$user->email}}">
                            </p>
                        </div>
                        <div class="field">
                            <label for="password" class="label">Password</label>
                            @if (!(Route::current()->getName() === 'users.create'))
                                <div class="field">
                                    <b-radio type="is-info" name="password_options" v-model="password_options" native-value="keep">Do Not Change Password</b-radio>
                                </div>
                            @endif
                            <div class="field">
                                <b-radio type="is-info" name="password_options" v-model="password_options" native-value="auto">Auto-Generate New Password</b-radio>
                            </div>
                            <div class="field">
                                <b-radio type="is-info" name="password_options" v-model="password_options" native-value="manual">Manually Set New Password</b-radio>
                                <p class="control">
                                    <input type="text" class="input" pattern=".{6,}" title="Six or more characters" name="password" id="password" v-if="password_options == 'manual'" placeholder="Manually give a password to this user">
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end of .column -->
            <div class="column is-paddingless">
                <div class="card full-height">
                    <div class="card-content">                    
                        <label for="roles" class="label">Roles:</label>
                        <input type="hidden" name="roles[]" :value="item" v-for="item in rolesSelected" v-if="rolesSelected"/>
                        @foreach ($roles as $role)
                            <div class="field">
                                <b-checkbox type="is-info" v-model="rolesSelected" :native-value="{{$role->id}}">{{$role->display_name}}</b-checkbox>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script>
    var app = new Vue({
        el: '#app',
        data: {
            password_options: "{{Route::current()->getName() === 'users.create'?'auto':'keep'}}",
            rolesSelected: {!! Route::current()->getName() === 'users.create'?json_encode([]):$user->roles->pluck('id') !!}
        }
    });
    </script>
@endsection

resources/views/back-end/users/create.blade.php
@extends('layouts.manage')

@section('content')
  <div class="flex-container">
    <div class="columns m-t-10">
      <div class="column">
        <h1 class="title">Create New User</h1>
        @if ($errors->any())
          <div class="is-size-6 has-text-danger has-text-weight-bold">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
        @endif
      </div>
    </div>
    <hr class="m-t-0">
    <form action="{{route('users.store')}}" method="POST">
      {{csrf_field()}}
      <div class="columns">
        <div class="column">
          <div class="field">
            <label for="name" class="label">Name</label>
            <p class="control">
              <input type="text" class="input" name="display_name" id="name">
            </p>
          </div>
          <div class="field">
            <label for="username" class="label">Username</label>
            <p class="control">
              <input type="text" class="input" name="name" id="username">
            </p>
          </div>
          <div class="field">
            <label for="email" class="label">Email:</label>
            <p class="control">
              <input type="text" class="input" name="email" id="email">
            </p>
          </div>
          <div class="field">
            <label for="password" class="label">Password</label>
            <p class="control">
              <input type="text" class="input" name="password" id="password" v-if="!auto_password" placeholder="Manually give a password to this user">
              <b-checkbox type="is-info" name="auto_generate" class="m-t-15" v-model="auto_password">Auto Generate Password</b-checkbox>
            </p>
          </div>
        </div> <!-- end of .column -->
        <div class="column">
          <label for="roles" class="label">Roles:</label>
          <input type="hidden" name="roles[]" :value="item" v-for="item in rolesSelected"/>
            @foreach ($roles as $role)
              <div class="field">
                <b-checkbox type="is-info" v-model="rolesSelected" :native-value="{{$role->id}}">{{$role->display_name}}</b-checkbox>
              </div>
            @endforeach
        </div>
      </div> <!-- end of .columns for forms -->
      <div class="columns">
        <div class="column">
          <hr />
          <button class="button is-info is-pulled-right" style="width: 250px;">Create New User</button>
        </div>
      </div>
    </form>
  </div> <!-- end of .flex-container -->
@endsection

@section('scripts')
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        auto_password: true,
        rolesSelected: []
      }
    });
  </script>
@endsection

resources/views/back-end/users/edit.blade.php
@extends('layouts.manage')

@section('content')
    <div class="flex-container">
        <div class="columns m-t-10">
            <div class="column">
                <h1 class="title">Edit User</h1>
            </div>
        </div>
        <hr class="m-t-0">
        <form action="{{route('users.update', $user->id)}}" method="POST">
            {{method_field('PUT')}}
            {{csrf_field()}}
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="name" class="label">Name:</label>
                        <p class="control">
                            <input type="text" class="input" name="display_name" id="name" value="{{$user->display_name}}">
                        </p>
                    </div>
                    <div class="field">
                        <label for="username" class="label">Username:</label>
                        <p class="control">
                            <input type="text" class="input" name="name" id="username" value="{{$user->name}}">
                        </p>
                    </div>
                    <div class="field">
                        <label for="email" class="label">Email:</label>
                        <p class="control">
                            <input type="text" class="input" name="email" id="email" value="{{$user->email}}">
                        </p>
                    </div>
                    <div class="field">
                        <label for="password" class="label">Password</label>
                        <div class="field">
                            <b-radio type="is-info" name="password_options" v-model="password_options" native-value="keep">Do Not Change Password</b-radio>
                        </div>
                        <div class="field">
                            <b-radio type="is-info" name="password_options" v-model="password_options" native-value="auto">Auto-Generate New Password</b-radio>
                        </div>
                        <div class="field">
                            <b-radio type="is-info" name="password_options" v-model="password_options" native-value="manual">Manually Set New Password</b-radio>
                            <p class="control">
                                <input type="text" class="input" name="password" id="password" v-if="password_options == 'manual'" placeholder="Manually give a password to this user">
                            </p>
                        </div>
                    </div>
                </div> <!-- end of .column -->
                <div class="column">
                    <label for="roles" class="label">Roles:</label>
                    <input type="hidden" name="roles" :value="rolesSelected" />
                    @foreach ($roles as $role)
                        <div class="field">
                            <b-checkbox type="is-info" v-model="rolesSelected" :native-value="{{$role->id}}">{{$role->display_name}}</b-checkbox>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <hr />
                    <button class="button is-info is-pulled-right"><i class="fa fa-pencil m-r-10"></i> Edit User</button>
                </div>
            </div>
        </form>
    </div> <!-- end of .flex-container -->
@endsection

@section('scripts')
    <script>
    var app = new Vue({
        el: '#app',
        data: {
            password_options: 'keep',
            rolesSelected: {!! $user->roles->pluck('id') !!}
        }
    });
    </script>
@endsection

resources/views/back-end/users/index.blade.php
@extends('layouts.manage', ['title_text' => '<i class="fa fa-user-plus"></i>', 'item_type' => 'Users',
'customButton' => '<a href="'.route('users.create').'" class="button is-warning is-pulled-right"><i class="fa fa-user-plus m-r-10"></i>Create User</a>'
])
@section('content')
  <div class="card">
    <div class="card-content">
      <table class="table is-narrow">
        <thead>
          <tr>
            <th>id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Date Created</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @foreach ($users as $user)
          <tr>
            <th>{{$user->id}}</th>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>{{$user->created_at->toFormattedDateString()}}</td>
            <td class="has-text-centered tools-bar" style="width: 150px;">
              @permission('read-users')
              <a class="button is-success" href="{{route('users.show', $user->id)}}">
                <i class="fa fa-eye"></i>
              </a>
              @endpermission
              @permission('update-users')
              <a class="button is-info" href="{{route('users.edit', $user->id)}}">
                <i class="fa fa-pencil"></i>
              </a>
              @endpermission
              {{-- <button class="button is-danger">
                    <i class="fa fa-trash"></i>
                  </button> --}}
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div> <!-- end of .card -->
  {{$users->links()}}
@endsection

resources/views/back-end/users/show.blade.php
@extends('layouts.manage', ['title_text' => '<i class="fa fa-user-plus m-r-10"></i>', 'item_type' => 'Users',
'customButton' => '<a href="'.route('users.edit', $user->id).'" class="button is-info is-pulled-right"><i class="fa fa-pencil m-r-10"></i>Edit User</a>'
])
@section('content')
    <div class="card p-b-25 m-b-25">
      <div class="card-content">
        <div class="columns">
          <div class="column">
            <div class="field">
              <label for="name" class="label">Name</label>
              <pre>{{$user->display_name}}</pre>
            </div>
            <div class="field">
              <label for="name" class="label">Username</label>
              <pre>{{$user->name}}</pre>
            </div>
            <div class="field">
              <div class="field">
                <label for="email" class="label">Email</label>
                <pre>{{$user->email}}</pre>
              </div>
            </div>
            @if(session('is_rand_pass_passed'))
            <div class="field">
              <div class="field">
                <label for="email" class="label">Random Password</label>
                <pre>{{session('pass')}}</pre>
              </div>
              <div class="field">
                <span class="has-text-danger has-text-weight-semibold">Remember this password. It will be shown only this time.</span>
              </div>
            </div>
            @endif
            <div class="field">
              <div class="field">
                <label for="email" class="label">Roles</label>
                <ul>
                  @forelse ($user->roles as $role)
                    <li>{{$role->display_name}} ({{$role->description}})</li>
                  @empty
                    <p>This user has not been assigned any roles yet</p>
                  @endforelse
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection